# Adapted from:
# https://gateway.envoyproxy.io/docs/tasks/security/ext-auth/#http-external-authorization-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-ext-auth
data:
  http-ext-auth.js: |
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-ext-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-ext-auth
  template:
    metadata:
      labels:
        app: http-ext-auth
    spec:
      containers:
      - name: http-ext-auth
        command:
        - python
        - /apps/auth.py
        image: python:3.14.3-slim
        ports:
        - containerPort: 9002
        volumeMounts:
          - mountPath: '/apps'
            name: 'apps'
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: authorization
              value: "Bearer token1"
            port: 9002
      volumes:
        - name: apps
          hostPath:
            path: /apps
---
apiVersion: v1
kind: Service
metadata:
  name: http-ext-auth
spec:
  selector:
    app: http-ext-auth
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
---
# This route will let us hit the auth server directly from outside the cluster.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auth
spec:
  parentRefs:
  - name: eg
  hostnames:
  - "www.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /auth
    backendRefs:
    - name: http-ext-auth
      port: 9002
